version: '2'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - reading-is-good-network
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - reading-is-good-network
  book-service:
    container_name: book-service
    build:
      context: book-service
      dockerfile: Dockerfile
    image: book-service:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8001:8001"
    networks:
      - reading-is-good-network
  customer-service:
    container_name: customer-service
    build:
      context: customer-service
      dockerfile: Dockerfile
    image: customer-service:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8002:8002"
    networks:
      - reading-is-good-network
  order-service:
    container_name: order-service
    build:
      context: order-service
      dockerfile: Dockerfile
    image: order-service:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8003:8003"
    networks:
      - reading-is-good-network
networks:
  reading-is-good-network:
    driver: bridge