server:
  port: 8002
spring:
  application:
    name: CUSTOMER-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

token:
  expiration_time: 6000000
  secret: hfgry463hf746hf573ydh475fhy5739
